In [ ]:
print('olá mundo!')

n1 = int(input('digite um numero: '))
n2 = int(input('digite outro numero: '))
s = n1 + n2
print(f'a soma de {n1} e {n2} é {s}') #abreviação da .format

olá mundo!
digite um numero: 356
digite outro numero: 23
a soma de 356 e 23 é 379

In [ ]:
n = input('digite um numero: ')
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
#há vários tipos de "is..... alguma coisa", vai depender da sua necessidade

digite um numero: 6575
True
False
True

In [ ]:
n = input('digite alguma coisa: ')
print ('o tipo primitivo é: ', type (n))
print ("É um numero? ", (n.isnumeric()))
print ("é alfabético? ", (n.isalpha()))
print ('é alfanumérico? ', (n.isalnum()))
print ('só tem espaços? ', (n.isspace()))
print ('está em maiúsculo? ', (n.isupper()))
print ('está em minusculo? ', (n.islower()))
print ('está capitalizado? ', (n.istitle())) #não está nem em minusculo nem em maiusculo

digite alguma coisa: Amor
o tipo primitivo é:  <class 'str'>
É um numero?  False
é alfabético?  True
é alfanumérico?  True
só tem espaços?  False
está em maiúsculo?  False
está em minusculo?  False
está capitalizado?  True

In [ ]:
print ('='*50)

==================================================

In [ ]:
n = input('qual o seu nome? ')
print (f'prazer em te conhecer {n:>30}') #entram 30 espaços antes de aparecer o nome, além de alinhar o texto a direita
print (f'prazer em te conhecer {n:^30}') #o texto fica centralizado
print (f'prazer em te conhecer {n:<30}')
print (f'prazer em te conhecer {n:~^30}')

qual o seu nome? ana
prazer em te conhecer                            ana
prazer em te conhecer              ana
prazer em te conhecer ana
prazer em te conhecer ~~~~~~~~~~~~~ana~~~~~~~~~~~~~~

In [ ]:
n1 = int(input('digite um numero: '))
n2 = int(input('digite outro: '))
div = n1/n2
print(f'a divisão de {n1} por {n2} é {div}')
print(f'a divisão de {n1} por {n2} é {div:.2f}') #esse é o comando para limitar o numero de casas apos a virgula

print(f'a divisão de {n1} por {n2} é {div}', end=' ') #esse comando no final evita a quebra de linha, para quando há frases muito grandes
print(f'a divisão de {n1} por {n2} é {div:.2f}')
print(f'a \n divisão \n de {n1} por {n2} é {div:.2f}') #esse comando \n faz a quebra de linha onde quisermos

digite um numero: 40
digite outro: 21
a divisão de 40 por 21 é 1.9047619047619047
a divisão de 40 por 21 é 1.90
a divisão de 40 por 21 é 1.9047619047619047 a divisão de 40 por 21 é 1.90
a
 divisão
 de 40 por 21 é 1.90

In [ ]:
n = int(input('digite um numero: '))
print(f'o antecessor de {n} é {(n-1)} e o sucessor é {(n+1)}')

digite um numero: 10
o antecessor de 10 é 9 e o sucessor é 11

In [ ]:
n= int(input('digite um numero: '))
print(f'o dobro de {n} é {(n*2)} ')
print(f'o triplo de {n} é {(n*3)} ')
print(f'a raiz quadrada de {n} é {(n**0.5):.2f}')
#pode ser feito assim, mas caso queira-se guardar os valores obtidos (dobro, triplo, raiz), deve-se criar variáveis para eles.
#criar variaveis gasta mais memoria, porém, na maioria dos casos é interessante guardar os resultados obtidos, portanto, sera utilizado variaveis.

digite um numero: 50
o dobro de 50 é 100
o triplo de 50 é 150
a raiz quadrada de 50 é 7.07

In [ ]:
n1 = float(input('digite a primeira nota: '))
n2 = float(input('digite a segunda nota: '))
print(f'a média das notas é: {(n1+n2)/2:.1f} ')

digite a primeira nota: 4.3
digite a segunda nota: 5.9
a média das notas é: 5.1

In [ ]:
n = float(input('digite uma distância em metros: '))
print(f'{n} m em km é {n/1000:.5f}, em hm é {n/100:.1f}, em dam é {n/10:.1f}, em dm é {n*10:.1f},', end=' ')
print(f'em cm é {n*100:.1f} e em mm é {n*1000:.1f}')

print(f'{n} m em km é {n/1000:.5f},\n em hm é {n/100:.1f},\n em dam é {n/10:.0f},\n em dm é {n*10:.0f},\n', end=' ')
print(f'em cm é {n*100:.0f}\n e em mm é {n*1000:.0f}')

digite uma distância em metros: 500
500.0 m em km é 0.50000, em hm é 5.0, em dam é 50.0, em dm é 5000.0, em cm é 50000.0 e em mm é 500000.0
500.0 m em km é 0.50000,
 em hm é 5.0,
 em dam é 50,
 em dm é 5000,
 em cm é 50000
 e em mm é 500000

In [ ]:
n = int(input('digite um numero para ver sua tabuada: '))
print('='*50)
print(f'{n} x 1 = {n*1:>10}')
print(f'{n} x 2 = {n*2:>10}')
print(f'{n} x 3 = {n*3:>10}')
print(f'{n} x 4 = {n*4:>10}')
print(f'{n} x 5 = {n*5:>10}')
print(f'{n} x 6 = {n*6:>10}')
print(f'{n} x 7 = {n*7:>10}')
print(f'{n} x 8 = {n*8:>10}')
print(f'{n} x 9 = {n*9:>10}')
print(f'{n} x 10 = {n*10:>9}')
print('='*50)

digite um numero para ver sua tabuada: 243
==================================================
243 x 1 =        243
243 x 2 =        486
243 x 3 =        729
243 x 4 =        972
243 x 5 =       1215
243 x 6 =       1458
243 x 7 =       1701
243 x 8 =       1944
243 x 9 =       2187
243 x 10 =      2430
==================================================

In [ ]:
n = float(input('quanto dinheiro você tem na carteira? '))
print(f'com R$ {n} você pode comprar US$ {(n/4.94):.2f}')

quanto dinheiro você tem na carteira? 50
com R$ 50.0 você pode comprar US$ 10.12

In [ ]:
print('vamos pintar!')
n1 = float(input('qual a largura da parede? (em m) '))
n2 = float(input('qual a altura da parede? (em m) '))
area = (n1*n2)
print(f'essa parede possui uma área de {area} m² ')
litros = area/5
print(f'considerando um rendimento de 5 m² por litro de tinta, para pintar essa parede você vai precisar de {litros} litros de tinta')

vamos pintar!
qual a largura da parede? (em m) 80
qual a altura da parede? (em m) 56
essa parede possui uma área de 4480.0 m²
considerando um rendimento de 5 m² por litro de tinta, para pintar essa parede você vai precisar de 896.0 litros de tinta

In [ ]:
n1 = float(input('qual o preço do produto? R$ '))
n2 = float(input('qual será o percentual de desconto? em % '))
print(f'o produto que custava R$ {n1:.2f}, com o desconto de {n2:.0f}%, custará R$ {n1-(n1*(n2/100)):.2f}')

qual o preço do produto? R$ 56.70
qual será o percentual de desconto? em % 15
o produto que custava R$ 56.70, com o desconto de 15%, custará R$ 48.20

In [ ]:
t = float(input('qual a temperatura? '))
print(f'{t:.0f} graus celsius corresponde a {(t*1.8)+32:.1f}°F')

qual a temperatura? 45
45 graus celsius corresponde a 113.0°F

In [ ]:
km = float(input("quantos km foram percorridos? "))
D = int(input("por quantos dias utilizou o veículo? "))
print(f'o valor a pagar pelo aluguel do carro é de: R$ {(km*0.15)+(D*60):.2f}')

quantos km foram percorridos? 78
por quantos dias utilizou o veículo? 4
o valor a pagar pelo aluguel do carro é de: R$ 251.70

In [ ]:
from math import sqrt, ceil
n = int(input("digite um numero: "))
raiz = math.sqrt(n)
print(f'a raiz de {n} arredondada é {math.ceil(raiz)}')

digite um numero: 54
a raiz de 54 é 8

In [ ]:
from math import trunc
n = float(input('digite um numero: '))
print(f'o numero {n} tem a parte inteira igual a {trunc(n)}')

digite um numero: 4.6
o numero 4.6 tem a parte inteira igual a 4

In [ ]:
n = float(input('digite um numero: '))
print(f'o numero {n} tem parte inteira igual a {n:.0f}')

digite um numero: 8.45
o numero 8.45 tem parte inteira igual a 8

In [ ]:
n = float(input('digite um numero: '))
print(f'o numero {n} tem parte inteira igual a {int(n)}')    #repare que há varios modos de resolver um problema

digite um numero: 4.67
o numero 4.67 tem parte inteira igual a 4

In [ ]:
co = float(input('digite o cateto oposto: '))
ca = float(input('digite o cateto adjacente: '))
hip = ((co**2)+(ca**2))**(1/2)
print(f'a hipotenusa é igual a {hip:.1f}')

digite o cateto oposto: 4
digite o cateto adjacente: 7
a hipotenusa é igual a 8.1

In [ ]:
from math import hypot
co = float(input('digite o cateto oposto: '))
ca = float(input('digite o cateto adjacente: '))
hip = hypot(co, ca)
print(f'a hipotenusa é igual a {hip:.1f}')

digite o cateto oposto: 4
digite o cateto adjacente: 7
a hipotenusa é igual a 8.1

In [ ]:
from math import sin, cos, tan, radians
n = float(input('digite um valor de angulo: '))
print(f'o seno desse numero é: {sin(radians(n)):.2f}')
print(f'o cosseno desse numero e´: {cos(radians(n)):.2f}')
print(f'a tangente desse numero é: {tan(radians(n)):.2f}')

digite um valor de angulo: 30
o seno desse numero é: 0.50
o cosseno desse numero e´: 0.87
a tangente desse numero é: 0.58

In [ ]:
import random
quanti = int(input('quantos nomes quer sortear? '))
for i in range(1, quanti + 1):
  nomes = [str(input(f'digite o {i}º nome: '))]
print('o nome sorteado foi: ', random.choice(nomes)) #ou pode usar somente o choice(nome), caso especifique na importação do modulo
#não sei se esta correto, so cai joao no sorteio

quantos nomes quer sortear? 3
digite o 1º nome: maria
digite o 2º nome: jose
digite o 3º nome: joao
o nome sorteado foi:  joao

In [ ]:
from random import choice
n1 = str(input('nome do primeiro aluno: '))
n2 = str(input('nome do segundo aluno: '))
n3 = str(input('nome do terceiro aluno: '))
n4 = str(input('nome do quarto aluno: '))
lista = [n1, n2, n3, n4]
print(f'o aluno escolhido foi: {choice(lista)}')

nome do primeiro aluno: maria
nome do segundo aluno: jose
nome do terceiro aluno: joao
nome do quarto aluno: katarina
o aluno escolhido foi: maria

In [ ]:
from random import shuffle
n1 = str(input('nome do primeiro aluno: '))
n2 = str(input('nome do segundo aluno: '))
n3 = str(input('nome do terceiro aluno: '))
n4 = str(input('nome do quarto aluno: '))
lista = [n1, n2, n3, n4]
shuffle(lista)
print(f'a ordem de apresentação é: {lista}')

nome do primeiro aluno: maria
nome do segundo aluno: ygona
nome do terceiro aluno: afonsinha
nome do quarto aluno: barbie
a ordem de apresentação é: ['maria', 'barbie', 'afonsinha', 'ygona']

In [ ]:
pygame

In [ ]:
frase = 'curso em video python'
#fatiamento
print(frase[9])
print(frase[9:13])
print(frase[9:21:2])  #pulando de dois em dois
print(frase[:5])
print(frase[15:])
print(frase[9::3])     #do nove até o final pulando de 3 em 3

#análise
print(len(frase))    #quantos caracteres tem
print(frase.count('o'))           #quantos 'o' minusculos tem
print(frase.find('deo'))      #indica em qual caractere começou o 'deo' na string
print(frase.count('o', 0, 13))     #quantos 'o' minusculos tem do caracter zero ao 13
print('curso' in frase)   #se existe a palavra 'curso' na string
print('android' in frase)  #se existe a palavra 'android' na string

#transformação
print(frase.replace('curso','Curso')) #autoexplicativo
print(frase.upper())
print(frase.lower())
print(frase.capitalize())  #só o primeiro caractere vai ficar em maiusculo
print(frase.title())

v
vide
vdopto
curso
python
veph
21
3
11
1
True
False
Curso em video python
CURSO EM VIDEO PYTHON
curso em video python
Curso em video python
Curso Em Video Python

In [ ]:
frase = '   Aprenda python  '

In [ ]:
print(frase.strip())   #remove os espaços inuteis, no inicio e no final da string
print(frase.rstrip())  #tira espaços inuteis a direita
print(frase.lstrip())  #tira espaços inuteis a esquerda

frase = 'curso em video python'
#divisão
print(frase.split()) #divide uma string em uma lista, cada palavra vai receber uma indexação, e não cada caractere

#junção
print(".".join(frase))

curso em video python
curso em video python
curso em video python
['curso', 'em', 'video', 'python']
c.u.r.s.o. .e.m. .v.i.d.e.o. .p.y.t.h.o.n

In [ ]:
#para printar textos grandes
print("""Dime cómo hacemos
Si tú me deseas y yo a ti también
Hace rato te quiero comer
Di qué vas a hacer""")

Dime cómo hacemos
Si tú me deseas y yo a ti también
Hace rato te quiero comer
Di qué vas a hacer

In [ ]:
dividido = frase.split()
print(dividido[3]) #'python' é o item 3 na divisão que o split faz

python

In [ ]:
nome = str(input('digite seu nome: ')).strip()
print('analisando seu nome...')
print('seu nome em letras maiúsculas é ', nome.upper())
print('seu nome em letras minúsculas é ', nome.lower())
print('seu nome tem ao todo ', (len(nome)-nome.count(' ')))
divisao = nome.split()
print(f'seu primeiro nome é {divisao[0]} e ele tem {len(divisao [0])} letras')
#nome.find(" ")         #para achar o primeiro nome também poderia ter usado esse

digite seu nome: Marcos Vinicius Alves Gomes
analisando seu nome...
seu nome em letras maiúsculas é  MARCOS VINICIUS ALVES GOMES
seu nome em letras minúsculas é  marcos vinicius alves gomes
seu nome tem ao todo  24
seu primeiro nome é Marcos e ele tem 6 letras

In [ ]:
n = int(input('informe um numero: '))
u = n // 1 % 10
d = n // 10 % 10
c = n // 100 % 10
m = n // 1000 % 10

print('analisando o numero...')
print(f'unidade: {u}')
print(f'dezena: {d}')
print(f'centena: {c}')
print(f'milhar: {m}')

informe um numero: 89
analisando o numero...
unidade: 9
dezena: 8
centena: 0
milhar: 0

para trabalhar com cores
no python, para style nos temos os codigos:
0 sem estilo nenhum
1 bold (negrito)
4 underline (sublinhado)
7 negativa (inverte???)

para text, temos as cores com codigos do 30 ao 37 (é possivel mais cores usando uma biblioteca)
para back, temos as cores para background, que vão de 40 a 47, mas são as mesmas cores padrao das de texto

In [ ]:
\033[0;33;44m     #apos o colchete, o primeiro numero representa style, o segundo text, e o terceiro back

In [ ]:
print('\033[1;31;43mminha primeira coloração\033[m')

minha primeira coloração

IF e ELSE

In [ ]:
n1 = float(input('digite a primeira nota: '))
n2 = float(input('digite a segunda nota: '))
m = (n1+n2)/2
print(f'a sua média foi de {m:.1f}')
print('Parabéns' if m>=6 else 'Estude mais!')

digite a primeira nota: 5
digite a segunda nota: 8
a sua média foi de 6.5
Parabéns

In [ ]:
from random import randint
from time import sleep
computador = randint(0, 5)
print('vou pensar em um numero entre 0 e 5, tente adivinhar')
jogador = int(input('Em que numero eu pensei? '))
print('processando...')
sleep(3)     #faz o computador ficar parado por x segundos
if jogador == computador:
  print('Parabéns, você acertou!')
else:
  print(f'Não foi dessa vez! o numero que eu pensei foi {computador}')

vou pensar em um numero entre 0 e 5, tente adivinhar
Em que numero eu pensei? 3
processando...
Não foi dessa vez! o numero que eu pensei foi 2

In [ ]:
vel = float(input('qual a velocidade? '))
if vel <= 80:
  print('tudo certo, siga sua viagem!')
else:
  multa = ((vel-80)*7)
  print(f'MULTADO!, você excedeu o limite de velocidade!, sua multa será de R$ {multa:.2f}')

qual a velocidade? 120
MULTADO!, você excedeu o limite de velocidade!, sua multa será de 280.0

In [ ]:
N = int(input('digite um numero: '))
if N % 2 == 0:
  print(f'{N} é par')
else:
  print(f'{N} é impar')

digite um numero: 9
9 é impar

In [ ]:
D = float(input('qual a distância da viagem? em Km '))
if D > 200:
  print(f'A passagem custará R$ {D*0.45:.2f}')
else:
  print(f'A passagem custará R$ {D*0.50:.2f}')

qual a distância da viagem? em Km 300
A passagem custará R$ 135.0

In [ ]:
from datetime import date
ano = int(input('qual ano quer analisar? digite 0 para analisar o ano atual '))
if ano == 0:
  ano = date.today().year
if ano % 4 == 0 and ano % 100 != 0 or ano % 400 != 0:
  print(f'{ano} é bissexto')
else:
  print(f'{ano} não é bissexto')

qual ano quer analisar? digite 0 para analisar o ano atual2016
2016 é bissexto

In [ ]:
a = int(input('digite o primeiro valor: '))
b = int(input('digite o segundo valor: '))
c = int(input('digite o terceiro valor: '))

menor = a
if b < a and b < c:
  menor = b
if c < b and c < a:
  menor = c

maior = a
if b > a and b > c:
  maior = b
if c > b and c > a:
  maior = c

print(f'o maior valor digitado foi {maior}')
print(f'o menor valor digitado foi {menor}')

digite o ´rimeiro valor: 7
digite o segundo valor: 78
digite o terceiro valor: 3
o maior valor digitado foi 78
o menor valor digitado foi 3

In [ ]:
sal = float(input('qual o salário? '))
if sal <= 1250:
  Nsal = sal*1.15
else:
  Nsal = sal*1.1
print(f'Para o salário de R$ {sal} o novo valor a receber será R$ {Nsal:.2f}')

qual o salário? 1820
Para o salário de R$ 1820.0 o novo valor a receber será R$ 2002.00

In [ ]:
Casa = float(input('Qual o valor da casa? '))
sal = float(input('Qual o valor do seu salário? '))
anos = int(input('quantos anos de financiamento? '))
Parcela = Casa / (anos*12)
print(f'para pagar uma casa de R$ {Casa} em {anos} anos')
print(f'A prestação mensal será de R$ {Parcela:.2f}')
if Parcela > (sal*0.3):
  print('seu emprestimo foi negado!')
else:
  print('seu emprestimo está aprovado!')

Qual o valor da casa? 100000
Qual o valor do seu salário? 5300.52
quantos anos de financiamento? 10
para pagar uma casa de R$ 100000.0 em 10 anos
A prestação mensal será de R$ 833.33
seu emprestimo está aprovado!

In [ ]:
num = int(input('digite um numero inteiro: '))
print('''Escolha uma das bases para conversão:
1 - Converter para Binário
2 - Converter para Octal
3 - Converter para Hexadecimal''')
opcao = int(input('digite sua opção: '))
if opcao == 1:
  print(f'{num} convertido para binário é igual a {bin(num)[2:]}')
elif opcao == 2:
  print(f'{num} convertido para octal é igual a {oct(num)[2:]}')
elif opcao == 3:
  print(f'{num} convertico para hexadecimal é igual a {hex(num)[2:]}')
else:
  print('opção inválida, tente novamente')

digite um numero inteiro: 565
Escolha uma das bases para conversão:
1 - Converter para Binário
2 - Converter para Octal
3 - Converter para Hexadecimal
digite sua opção: 3
565 convertico para hexadecimal é igual a 235

In [ ]:
n1 = int(input('digite o primeiro numero: '))
n2 = int(input('digite o segundo numero: '))
if n1 > n2:
  print('o primeiro numero é maior que o segundo')
elif n2 > n1:
  print('o segundo numero é maior que o primeiro')
else:
  print('os numeros são iguais')

digite o primeiro numero: 2
digite o segundo numero: 5
o segundo numero é maior que o primeiro

In [ ]:
from datetime import date
atual = date.today().year
nasc = int(input('qual o ano do seu nascimento:? '))
idade = atual - nasc
print(f'quem nasceu em {nasc} tem {idade} em {atual}')
if idade == 18:
  print('você deve se alistar esse ano')
elif idade < 18:
  print(f'você ainda não tem 18, faltam {18-idade} anos para você se alistar')
else:
  extras = idade - 18
  print(f'você já devia ter se alistado, o seu ano de alistamento foi {atual - extras}')

qual o ano do seu nascimento:? 1987
quem nasceu em 1987 tem 35 em 2022
você já devia ter se alistado, o seu ano de alistamento foi 2005

In [ ]:
r1 = float(input('digite o primeiro segmento: '))
r2 = float(input('digite o segundo segmento: '))
r3 = float(input('digite o terceiro segmento: '))
if r1 < r2 + r3 and r2 < r1 + r3 and r3 < r1 + r2:
  print('os segmentos informados podem formar um triângulo ', end='')
  if r1 == r2 == r3:
    print('Equilatero')
  elif r1 != r2 != r3 != r1:
    print('escaleno')
  else:
    print('isóceles')
else:
  print('não podem formar triangulo')

digite o primeiro segmento: 5
digite o segundo segmento: 6
digite o terceiro segmento: 9
os segmentos informados podem formar um triângulo escaleno

In [ ]:
peso = float(input('digite seu peso em kg: '))
altura = float(input('digite sua altura em M: '))
imc = peso / (altura**2)
print(f'o seu IMC é de {imc:.1f}')
if imc < 18.5:
  print('Você está abaixo do peso normal')
elif imc < 25:
  print('você está no peso normal')
elif imc < 30:
  print('você está no sobrepeso')
elif imc < 40:
  print('você está obeso')
else:
  print('você está com obesidade morbida')

digite seu peso em kg: 90
digite sua altura em M: 1.60
o seu IMC é de 35.2
você está obeso

In [ ]:
#print('{:=^40}.format('loja da xana'))
print('='*20,'loja da xana','='*20)
preco = float(input('preço das compras: R$ '))
print('''formas de pagamento:
1 - a vista dinheiro/cheque
2 - a vista cartão
3 - 2x no credito
4 - 3x ou mais no credito''')
opcao = int(input('selecione sua opção: '))
if opcao == 1:
  print(f'o preço com o desconto de a vista sera R$ {preco-(preco*0.10):.2f}')
elif opcao == 2:
  print(f'o preço com o desconto de a vista no cartão será R$ {preco-(preco*0.5):.2f} ')
elif opcao == 3:
  print(f'parcelado em duas vezes no credito, o valor a se pagar permanece R$ {preço}')
else:
  print(f'parcelado de tres ou mais vezes no credito, o valor total a se pagar será de R$ {preco+(preco*0.20)}')

==================== loja da xana ====================
preço das compras: R$ 5623.88
formas de pagamento:
1 - a vista dinheiro/cheque
2 - a vista cartão
3 - 2x no credito
4 - 3x ou mais no credito
selecione sua opção: 4
parcelado de tres ou mais vezes no credito, o valor total a se pagar será de R$ 6748.656

In [ ]:
from random import randint
itens = ('pedra', 'papel', 'tesoura')
computador = randint(0,2)
print('''suas opções:
0 - pedra
1 - papel
2 - tesoura''')
jogador = int(input('qual a sua jogada? '))
print('-='*11)
print('computador jogou {}'.format(itens[computador]))
print('jogador jogou {}'.format(itens[jogador]))
print('-='*11)
if computador == 0:
  if jogador == 0:
    print('empate')
  elif jogador == 1:
    print('jogador venceu')
  elif jogador == 2:
    print('computador venceu')
elif computador == 1:
  if jogador == 0:
    print('computador venceu')
  elif jogador == 1:
    print('empate')
  elif jogador == 2:
    print('jogador venceu')
elif computador == 2:
  if jogador == 0:
    print('jogador venceu')
  elif jogador == 1:
    print('computador venceu')
  elif jogador == 2:
    print('empate')

suas opções:
0 - pedra
1 - papel
2 - tesoura
qual a sua jogada? 1
-=-=-=-=-=-=-=-=-=-=-=
computador jogou tesoura
jogador jogou papel
-=-=-=-=-=-=-=-=-=-=-=
computador venceu

WHILE E FOR

In [ ]:
for i in range(1,6):
  print('chupa meu cu')

chupa meu cu
chupa meu cu
chupa meu cu
chupa meu cu
chupa meu cu

In [ ]:
for i in range(1,7):
  print(i)
print ('--'*40)
for i in range(0,7):
  print(i)
print ('--'*40)
for i in range(7,0,-1):
  print(i)
print ('--'*40)
for i in range(0,7,2):
  print(i)

1
2
3
4
5
6
--------------------------------------------------------------------------------
0
1
2
3
4
5
6
--------------------------------------------------------------------------------
7
6
5
4
3
2
1
--------------------------------------------------------------------------------
0
2
4
6

In [ ]:
n = int(input('digite um numero: '))
for i in range(0,n+1):
  print(i)

digite um numero: 10
0
1
2
3
4
5
6
7
8
9
10

In [ ]:
s = 0
for i in range(0,5):
  n = int(input('digite um valor: '))
  s += n
print(f'a soma de todos os valores é: {s}')

digite um valor: 12
digite um valor: 3
digite um valor: 5
digite um valor: 66
digite um valor: 43
a soma de todos os valores é: 129

exercicios de FOR..

In [ ]:
from time import sleep
for cont in range(10, -1, -1):
  print(cont)
  sleep(1)
print('QUANDO A BUCETA DESCANSA, É AI QUE O CU TRABALHA! BEIJOH!')

10
9
8
7
6
5
4
3
2
1
0
QUANDO A BUCETA DESCANSA, É AI QUE O CU TRABALHA! BEIJOH!

In [ ]:
for n in range (1, 51):
  if n % 2 == 0:
    print(n, end=" ") # para a listagem ser na mesma linha, interessante

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50

In [ ]:
# ou
for n in range (2, 51, 2):
  print(".", end="") #para indicar uma operação sendo feita
  print(n, end=" ")

.2 .4 .6 .8 .10 .12 .14 .16 .18 .20 .22 .24 .26 .28 .30 .32 .34 .36 .38 .40 .42 .44 .46 .48 .50

In [ ]:
#soma dos impares entre 1 e 500 e que são divisiveis por 3
soma = 0
for c in range(1, 501, 2):
  if c % 3 == 0:
    soma += c
print('a soma de todos os valores solicitados é ', soma)

a soma de todos os valores solicitados é  20667

In [ ]:
n = int(input('digite um numero para ver sua tabuada: '))
for i in range (1, 11):
  print(f'{n} x {i} = {n*i}')

digite um numero para ver sua tabuada: 6
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

In [ ]:
soma = 0
cont = 0
for i in range(1,7):
  n = int(input(f'digite o {i}º valor: '))
  if n % 2 == 0:
    soma += n
    cont += 1
print(f'você informou {cont} numero pares e a soma deles é {soma}')

digite o 1º valor: 5
digite o 2º valor: 2
digite o 3º valor: 3
digite o 4º valor: 6
digite o 5º valor: 1
digite o 6º valor: 8
você informou 3 numero pares e a soma deles é 16

In [ ]:
primeiro = int(input('qual o primeiro termo? '))
razao = int(input('razão: '))
decimo = primeiro + (10 - 1) * razao
for c in range(primeiro, decimo + razao, razao):
  print(f'{c}', end=' ->')

qual o primeiro termo? 2
razão: 7
2 ->9 ->16 ->23 ->30 ->37 ->44 ->51 ->58 ->65 ->

In [ ]:
n = int(input('digite um numero: '))
tot = 0
for i in range(1, n+1):
  if n % i == 0:
    print('\033[33m', end='')
    tot += 1
  else:
    print('\033[31m', end='')
  print(f'{i}', end='')
print(f'\n\033[mO número {n} foi divisível {tot} vezes')
if tot == 2:
  print('e por isso ele é primo ')
else:
  print('e por isso ele não é primo')

digite um numero: 9
123456789
O número 9 foi divisível 3 vezes
e por isso ele não é primo

In [ ]:
frase = str(input('digite uma frase: ')).strip().upper()
palavras = frase.split()
junto = ''.join(palavras)
inverso = ''
for letra in range(len(junto)-1, -1, -1):
  inverso += junto[letra]
if inverso == junto:
  print('temos um palindromo')
else:
  print('não temos um palindromo')

digite uma frase: buceta
não temos um palindromo

In [ ]:
from datetime import date
atual = date.today().year
tot_menor = 0
for i in range(1, 7):
  nasc = int(input(f'em que ano a {i} pessoa nasceu? '))
  idade = atual - nasc
  print(f'essa pessoa tem {idade} anos de idade')
  if idade >= 18:
    print('é maior de idade')
  else:
    print('é menor de idade')
    tot_menor += 1
print(f'há {tot_menor} menores entre os digitados')

em que ano a 1 pessoa nasceu? 2000
essa pessoa tem 22 anos de idade
é maior de idade
em que ano a 2 pessoa nasceu? 1999
essa pessoa tem 23 anos de idade
é maior de idade
em que ano a 3 pessoa nasceu? 2006
essa pessoa tem 16 anos de idade
é menor de idade
em que ano a 4 pessoa nasceu? 2007
essa pessoa tem 15 anos de idade
é menor de idade
em que ano a 5 pessoa nasceu? 2005
essa pessoa tem 17 anos de idade
é menor de idade
em que ano a 6 pessoa nasceu? 2004
essa pessoa tem 18 anos de idade
é maior de idade
há 3 menores entre os digitados

In [ ]:
maior = 0
menor = 0
for p in range(1, 6):
  peso = float(input(f'peso da {p} pessoa: '))
  if p == 1:
    maior = peso
    menor = peso
  else:
    if p > maior:
      maior = peso
    if p < menor:
      menor = peso
print(f'o maior peso lido foi de {maior} kg')
print(f'o menor peso lido foi de {menor} kg')

peso da 1 pessoa: 1.85
peso da 2 pessoa: 96
peso da 3 pessoa: 5
peso da 4 pessoa: 15
peso da 5 pessoa: 85
o maior peso lido foi de 96.0 kg
o menor peso lido foi de 1.85 kg

In [ ]:
media = 0
velho = 0
jovens = 0
for i in range(1, 5):
  print('-'*10, f' {i}ª pessoa', '-'*10)
  nome = str(input('nome: '))
  idade = int(input('idade: '))
  sexo = str(input('sexo [M|F]: ')).strip().upper()
  media += idade
  if sexo == 'M':
    if idade > velho:
      velho = idade
      nomeVelho = nome
  if sexo == 'F' and idade < 20:
    jovens += 1
print(f'A média de idade do grupo é de: {(media/i):.1f} anos')
print(f'O homem mais velho se chama {nomeVelho} e sua idade é {velho} anos')
print(f'Ao todo são {jovens} mulheres com menos de 20 anos no grupo')

----------  1ª pessoa ----------
nome: Maria
idade: 16
sexo [M|F]: f
----------  2ª pessoa ----------
nome: José
idade: 54
sexo [M|F]: m
----------  3ª pessoa ----------
nome: Carlos
idade: 45
sexo [M|F]: M
A média de idade do grupo é de: 38.3 anos
O homem mais velho se chama José e sua idade é 54 anos
Ao todo são 1 mulheres com menos de 20 anos no grupo

aula de while

In [ ]:
c = 1
while c <= 10:
  print(c)
  c += 1

1
2
3
4
5
6
7
8
9
10

In [ ]:
r = 'S'
while r != 'N':
  n = int(input('digite um valor: '))
  r = str(input('quer continuar? (S/N) ')).upper()
  print(f'{n} capetas elegantes')

digite um valor: 3
quer continuar? (S/N) s
3 capetas elegantes
digite um valor: 343
quer continuar? (S/N) s
343 capetas elegantes
digite um valor: 657
quer continuar? (S/N) n
657 capetas elegantes

In [ ]:
n = 1
par = impar = 0
while n != 0:
  n = int(input('digite um valor: '))
  if n%2 == 0:
    par += 1
  else:
    impar +=1
print(f'você digitou {par} numeros pares e {impar} numeros impares')

digite um valor: 646
digite um valor: 4575
digite um valor: 888
digite um valor: 764
digite um valor: 4
digite um valor: 5
digite um valor: 6
digite um valor: 7
digite um valor: 99
digite um valor: 8
digite um valor: 0
você digitou 7 numero pares e 4 numeros impares

Exercicios de while

In [ ]:
sexo = str(input('qual o sexo da pessoa? (M/F) ')).strip().upper()[0]
while sexo != 'M' and sexo != 'F':
  sexo = str(input('entrada inválida, digite novamente: ')).strip().upper()[0]
print('sua resposta foi registrada!')

qual o sexo da pessoa? (M/F) k
entrada inválida, digite novamente: m
sua resposta foi registrada!

In [ ]:
from random import randint
computador = randint(1, 10)
print('sou o computador e vou pensar em um numero de 1 a 10, você terá que advinhar qual foi!')
acertou = False
palpite = 0
while not acertou:    #enquanto NÃO acertou, ou seja, nesse caso, enquanto não for (NÃO FALSE) haverá repetição
  jogador = int(input('qual o seu palpite? '))
  palpite += 1
  if jogador == computador:
    acertou = True
  elif jogador > computador:
    print('um pouco menor, tente novamente')
  elif jogador < computador:
    print('um pouco maior, tente novamente')
print(f'após {palpite} tentativas, você acertou!')

sou o computador e vou pensar em um numero de 1 a 10, você terá que advinhar qual foi!
qual o seu palpite? 7
um pouco menor, tente novamente
qual o seu palpite? 3
um pouco maior, tente novamente
qual o seu palpite? 5
um pouco menor, tente novamente
qual o seu palpite? 4
após 4 tentativas, você acertou!

In [ ]:
from time import sleep
n1 = int(input('Primeiro valor: '))
n2 = int(input('Segundo valor: '))
opcao = 0
while opcao != 5:
  print('''[1] somar
[2] multiplicar
[3] maior
[4] novos números
[5] sair do programa''')
  opcao = int(input('~~~~~ Qual sua opção? '))
  if opcao == 1:
    soma = n1 + n2
    print(f'A soma entre {n1} + {n2} é {soma}')
  elif opcao == 2:
    produto = n1*n2
    print(f'o resultado de {n1} x {n2} é {produto}')
  elif opcao == 3:
    if n1 > n2:
      maior = n1
    else:
      maior = n2
    print(f'entre {n1} e {n2} o maior valor é {maior}')
  elif opcao == 4:
    print('informe os numeros novamente')
    n1 = int(input('Primeiro valor: '))
    n2 = int(input('Segundo valor: '))
  elif opcao == 5:
    print('finalizando...')
  else:
    print('opção inválida, tente novamente')
  print('=~='*15)
  sleep(3)
print('fim do programa, vai pra puta que pariu')

Primeiro valor: 4
Segundo valor: 5
[1] somar
[2] multiplicar
[3] maior
[4] novos números
[5] sair do programa
~~~~~ Qual sua opção? 2
o resultado de 4 x 5 é 20
=~==~==~==~==~==~==~==~==~==~==~==~==~==~==~=
[1] somar
[2] multiplicar
[3] maior
[4] novos números
[5] sair do programa
~~~~~ Qual sua opção? 5
finalizando...
=~==~==~==~==~==~==~==~==~==~==~==~==~==~==~=
fim do programa, vai pra puta que pariu

In [ ]:
from math import factorial
n = int(input('digite um numero para calcular seu fatorial: '))
f = factorial(n)
print(f'o fatorial de {n} é {f}')

digite um numero para calcular seu fatorial: 6
o fatorial de 6 é 720

In [ ]:
n = int(input('digite um numero para calcular seu fatorial: '))
c = n
f = 1
print(f'calculando {n}! = ', end='')
while c > 0:
  print(f'{c}', end='')
  print('x' if c > 1 else ' = ', end='')
  f *= c
  c -= 1
print(f'{f}')

digite um numero para calcular seu fatorial: 8
calculando 8! = 8x7x6x5x4x3x2x1 = 40320

In [ ]:
pt = int(input('digite o primeiro termo da pa: '))
r = int(input('qual a razão da pa? '))
termo = pt
cont = 1
while cont <= 10:
  print(f'{termo} -> ', end='')
  termo += r
  cont += 1
print('FIM!')

digite o primeiro termo da pa: 0
qual a razão da pa? 5
0 -> 5 -> 10 -> 15 -> 20 -> 25 -> 30 -> 35 -> 40 -> 45 -> FIM!

In [ ]:
termo = int(input('Digite o primeiro termo da PA: '))
razão = int(input('Digite a razão da PA: '))
y = 1
n = termo + (10)*razão
while y != 0:
    while termo != n:
        print(termo, end = ' → ')
        termo += razão
    print('Pausa ☺')
    y = int(input('Mais quantos termos você deseja ver?: '))
    n = termo + y*razão
print('Fim!')

Digite o primeiro termo da PA: 5
Digite a razão da PA: 5
5 → 10 → 15 → 20 → 25 → 30 → 35 → 40 → 45 → 50 → Pausa ☺
Mais quantos termos você deseja ver?: 3
55 → 60 → 65 → Pausa ☺
Mais quantos termos você deseja ver?: 7
70 → 75 → 80 → 85 → 90 → 95 → 100 → Pausa ☺
Mais quantos termos você deseja ver?: 0
Fim!

In [ ]:
print('sequencia de fibonnaci')
n = int(input('quantos termos quer mostrar? '))
fib1 = 0
fib2 = 1
print(f'{fib1} -> {fib2} -> ', end='')
cont = 3
while cont <= n:
  fib3 = fib1 + fib2
  print(f'{fib3} -> ', end='')
  fib1 = fib2
  fib2 = fib3
  cont += 1
print(' fim!')

sequencia de fibonnaci
quantos termos quer mostrar? 15
0 -> 1 -> 1 -> 2 -> 3 -> 5 -> 8 -> 13 -> 21 -> 34 -> 55 -> 89 -> 144 -> 233 -> 377 ->  fim!

In [ ]:
s = cont = n = 0
while n != 999:
  s += n
  cont += 1
  n = int(input('digite um numero (999 para parar): '))
print(f'você digitou {cont} numeros e a soma entre eles é {s}')

digite um numero (999 para parar): 9
digite um numero (999 para parar): 6
digite um numero (999 para parar): 7
digite um numero (999 para parar): 4
digite um numero (999 para parar): 999
você digitou 5 numeros e a soma entre eles é 26

In [ ]:
resp = 'S'
s = cont = 0
while resp in 'S':
  n = int(input('digite um valor: '))
  resp = str(input('quer continuar? [S/N]: ')).strip().upper()
  if cont == 1:
    maior = menor = n
  elif n > maior:
    maior = n
  elif n < menor:
    menor = n
  s += n
  cont += 1
media = s/cont
print(f'foram digitados {cont} numeros, a média entre eles é {media:.1f}')
print(f'o maior valor digitado foi {maior} e o menor valor digitado foi {menor}')

digite um valor: 8
quer continuar? [S/N]: s
digite um valor: 7
quer continuar? [S/N]: s
digite um valor: 98
quer continuar? [S/N]: s
digite um valor: 2
quer continuar? [S/N]: n
foram digitados 4 numeros, a média entre eles é 28.8
o maior valor digitado foi 98 e o menor valor digitado foi 2

interrompendo repetições

In [ ]:
cont = 1
while True:
  print(cont, ' ', end='')
  cont += 1
print('Acabou')

In [ ]:
n = s = 0
while True:
  n = int(input('digite um número (999 para parar): '))
  if n == 999:
    break
  s += n
print(f'a soma vale {s}')
#dessa forma o 999 não vai entrar na soma

digite um número: 8
digite um número: 6
digite um número: 4
digite um número: 66
digite um número: 999
a soma vale 84

Exercicios interrupção de repetição

In [ ]:
cont = s = 0
while True:
  n = int(input('digite um número (999 para parar): '))
  if n == 999:
    break
  s += n
  cont += 1
print(f'a soma dos {cont} numeros digitados vale {s}')

digite um número (999 para parar): 5
digite um número (999 para parar): 3
digite um número (999 para parar): 4
digite um número (999 para parar): 999
a soma dos 3 numeros digitados vale 12

In [ ]:
from time import sleep
while True:
  n = int(input('quer ver a tabuada de qual numero? '))
  if n < 0:    #negativo para o laço de repetição
    break
  print('^~'*15)
  for i in range(1, 11):
    print(f'{n} x {i} = {n*i}')
    sleep(1)
  print('^~'*15)

quer ver a tabuada de qual numero? 4
^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~
quer ver a tabuada de qual numero? -8

In [ ]:
import random
print('~^'*20)
print('VAMOS JOGAR UM JOGO!')
print('~^'*20)
while True:
  v = int(input('digite um valor: '))
  pi = str(input('Par ou Impar? (P/I): ')).strip().upper()
  vcomp = random.randint(0,1000)
  tot = v + vcomp
  if tot % 2 == 0:
    print(f'você jogou {v} e o computador {vcomp}, no total deu {tot} que é Par!')
    if pi == 'P':
      print('você venceu!')
    elif pi == 'I':
      print('você perdeu!')
  elif tot % 2 != 0:
    print(f'você jogou {v} e o computador {vcomp}, no total deu {tot} que é Impar!')
    if pi == 'I':
      print('você ganhou!')
    elif pi == 'P':
      print('você perdeu!')
  print('~^'*20)
  parada = str(input('quer continuar? (S/N) ')).strip().upper()
  if parada == "S":
    continue
  elif parada == "N":
    print('Fim do jogo!')
    break

~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
VAMOS JOGAR UM JOGO!
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
digite um valor: 7
Par ou Impar? (P/I): i
você jogou 7 e o computador 136, no total deu 143 que é Impar!
você ganhou!
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
quer continuar? (S/N) n
Fim do jogo!

In [ ]:
hom = mul = maior = 0
while True:
  print('~^'*20)
  print('Cadastro de Pessoa')
  print('~^'*20)
  sexo = str(input('sexo: (M/F) ')).strip().upper()
  idade = int(input('idade: '))
  if sexo == 'M':
    hom += 1
  if idade > 18:
    maior += 1
  if sexo == 'F' and idade < 20:
    mul += 1
  print('cadastro bem sucedido')
  print('~^'*20)
  parada = str(input('quer continuar? (S/N): ')).strip().upper()
  print('')
  if parada == 'S':
    continue
  elif parada == 'N':
    print(f'total de pessoas com mais de 18 anos: {maior}')
    print(f'total de homens cadastrados: {hom}')
    print(f'total de mulheres com menos de 20 anos: {mul}')
    break

~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
Cadastro de Pessoa
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
sexo: (M/F) f
idade: 5
cadastro bem sucedido
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
quer continuar? (S/N): s

~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
Cadastro de Pessoa
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
sexo: (M/F) f
idade: 67
cadastro bem sucedido
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
quer continuar? (S/N): s

~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
Cadastro de Pessoa
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
sexo: (M/F) m
idade: 6
cadastro bem sucedido
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
quer continuar? (S/N): s

~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
Cadastro de Pessoa
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
sexo: (M/F) m
idade: 34
cadastro bem sucedido
~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
quer continuar? (S/N): n

total de pessoas com mais de 18 anos: 2
total de homens cadastrados: 2
total de mulheres com menos de 20 anos: 1

In [ ]:
print('#-'*20)
print('Loja Super Bucetão')
print('#-'*20)
menor = 99999
precoMenor = cont = totPreco = 0
nomeMenor = ''

while True:
  prod = str(input('nome do produto: '))
  preco = float(input('valor do produto: '))
  print('#-'*20)
  if preco < menor:
    nomeMenor = prod
    precoMenor = preco
  if preco > 1000:
    cont += 1
  totPreco += preco
  parada = str(input('quer continuar? (S/N): ')).strip().upper()
  if parada == 'S':
    continue
  elif parada == 'N':
    print(f'o total da compra foi {totPreco}')
    print(f'temos {cont} produto com valor maior que mil reais')
    print(f'o produto mais barato foi {nomeMenor} custando {precoMenor}')
    break

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
Loja Super Bucetão
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
nome do produto: melancia
valor do produto: 3
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
quer continuar? (S/N): s
nome do produto: maca
valor do produto: 6
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
quer continuar? (S/N): s
nome do produto: pera
valor do produto: 7
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
quer continuar? (S/N): n
o total da compra foi 16.0
temos 0 produto com valor maior que mil reais
o produto mais barato foi pera custando 7.0

In [ ]:
#ou
total = totmil = menor = cont = 0
nomemenor = ' '
while True:
  prod = str(input('nome do produto: '))
  preco = float(input('preço: '))
  total += preco
  cont += 1
  if preco > 1000:
    totmil += 1
  if cont == 1 or preco < menor:
    menor = preco
    nomemenor = prod
  resp = ' '
  while resp not in 'SN':
    resp = str(input('quer continuar? (S/N): ')).strip().upper()
  if resp == 'N':
    break
print('-'*10, 'fim do programa', '-'*10)
print(f'o total da compra foi de: {total}')
print(f'há {totmil} produtos custando mais de mil reais')
print(f'o produto mais barato foi {nomemenor}')
#esse cont foi usado para saber se é o primeiro produto, se for, também será o produto mais barato
#isso é pra não iniciar a variavel com 9999999

nome do produto: macarrão
preço: 2
quer continuar? (S/N): s
nome do produto: feijão
preço: 6
quer continuar? (S/N): n
---------- fim do programa ----------
o total da compra foi de: 8.0
há 0 produtos custando mais de mil reais
o produto mais barato foi macarrão

In [ ]:
print('$'*30)
print('{:^30}'.format('Banco Xeremil'))
print('$'*30)
print('')
saque = int(input('qual valor quer sacar? (apenas valores pares) R$ '))
resto50 = resto20 = resto10 = resto5 = resto2 = 0

N50 = saque // 50
resto50 = saque % 50
print(f'total de {N50} notas de 50 reais')

if resto50 != 0:
  N20 = resto50 // 20
  resto20 = resto50 % 20
  print(f'total de {N20} notas de 20 reais')

if resto20 != 0:
  N10 = resto20 // 10
  resto10 = resto20 % 10
  print(f'total de {N10} notas de 10 reais')

if resto10 != 0:
  N5 = resto10 // 5
  resto5 = resto10 % 5
  print(f'total de {N5} notas de 5 reais')

if resto5 != 0:
  N2 = resto5 // 2
  resto2 = resto5 // 2
  print(f'total de {N2} notas de 2 reais')
  print(' ')
print('$'*5, 'Obrigado por usar o Banco Xeremil!', '$'*5)

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        Banco Xeremil
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

qual valor quer sacar? (apenas valores pares) R$ 4567
total de 91 notas de 50 reais
total de 0 notas de 20 reais
total de 1 notas de 10 reais
total de 1 notas de 5 reais
total de 1 notas de 2 reais

$$$$$ Obrigado por usar o Banco Xeremil! $$$$$

In [ ]:
#guanabara resolução
print('$'*30)
print('{:^30}'.format('Banco Xeremil'))
print('$'*30)
print('')
valor = int(input('qual valor quer sacar? R$ '))
total = valor
ced = 50
totced = 0
while True:
  if total >= ced:
    total -= ced
    totced += 1
  else:
    if totced > 0:
      print(f'total de {totced} notas de {ced} reais')
    if ced == 50:
      ced = 20
    elif ced == 20:
      ced = 10
    elif ced == 10:
      ced = 1
    totced = 0
    if total == 0:
      break
print(' ')
print('$'*30)
print('Obrigado por usar o xeremil!')
print('$'*30)

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        Banco Xeremil
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

qual valor quer sacar? R$ 377000
total de 7540 notas de 50 reais

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Obrigado por usar o xeremil!
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

variáveis compostas: tuplas, listas, dicionários

TUPLAS

In [ ]:
#as tuplas são imutáveis
lanche = ('hamburger', 'suco', 'pizza', 'pudim')
print(lanche)
print(lanche[1])
print(lanche[-2])
print(lanche[-1])
print(lanche[2:])
print(lanche[:2]) #o segundo é excluido, como sempre no python
print(lanche[1:3]) #o terceiro é excluido, como sempre no python

('hamburger', 'suco', 'pizza', 'pudim')
suco
pizza
pudim
('pizza', 'pudim')
('hamburger', 'suco')
('suco', 'pizza')

In [ ]:
from time import sleep
lanche = ('hamburger', 'suco', 'pizza', 'pudim')
for comida in lanche:
  print(f'eu vou comer {comida}')
  sleep(2)
print('comi pra caramba!')

eu vou comer hamburger
eu vou comer suco
eu vou comer pizza
eu vou comer pudim
comi pra caramba!

In [ ]:
print(len(lanche))

4

In [ ]:
lanche = ('hamburger', 'suco', 'pizza', 'pudim', 'batata frita')
for cont in range(0, len(lanche)):
  print(lanche[cont])
print('comi pra caramba!')

hamburger
suco
pizza
pudim
batata frita
comi pra caramba!

In [ ]:
lanche = ('hamburger', 'suco', 'pizza', 'pudim', 'batata frita')
for cont in range(0, len(lanche)):         #usando range
  print(lanche[cont], f'na posição {cont}')
#ou
for pos, comida in enumerate(lanche):       #usando enumerate
  print(f'eu vou comer {comida} na posição {pos}')
print('comi pra caramba!')

hamburger na posição 0
suco na posição 1
pizza na posição 2
pudim na posição 3
batata frita na posição 4
eu vou comer hamburger na posição 0
eu vou comer suco na posição 1
eu vou comer pizza na posição 2
eu vou comer pudim na posição 3
eu vou comer batata frita na posição 4
comi pra caramba!

In [ ]:
print(sorted(lanche)) #fez uma lista ordenada
print(lanche)

['batata frita', 'hamburger', 'pizza', 'pudim', 'suco']
('hamburger', 'suco', 'pizza', 'pudim', 'batata frita')

In [ ]:
a = (2,5,4)
b = (5,8,1,2)
c = b + a
print(c)
print(len(c))
print(c.count(5))  #quantas vezes aparece o numero 5
print(c.index(4))

(5, 8, 1, 2, 2, 5, 4)
7
2
6

In [ ]:
#podem ser inseridos dados diferentes dentro de uma mesma tupla
#não é possivel deletar somente um item da tupla, só a tupla inteira
pessoa = ('Gustavo', 39, 'M', 99.88)
#  del(pessoa[0])  não é possivel
#  del(pessoa)
print(pessoa)

Exercicios tuplas

In [ ]:
#numeros por extenso
numeros = ('zero', 'um', 'dois', 'três', 'quatro', 'cinco', 'seis',
           'sete', 'oito', 'nove', 'dez', 'onze', 'doze', 'treze',
           'quatorze', 'quinze', 'dezesseis', 'dezessete', 'dezoito',
           'dezenove', 'vinte')
resp = 'S'
while True:
  n = int(input('digite um numero entre 0 e 20: '))
  if 0 <= n <= 20:
    print(f'você digitou o numero {numeros[n]}')
    resp = str(input('quer continuar? (S/N) ')).strip().upper()
    if resp == "N":
      print('Fim da Execução!')
      break
    else:
      continue
  else:
    print('número fora do intervalo, tente novamente')

digite um numero entre 0 e 20: 2
você digitou o numero dois
quer continuar? (S/N) s
digite um numero entre 0 e 20: 35
número fora do intervalo, tente novamente
digite um numero entre 0 e 20: 18
você digitou o numero dezoito
quer continuar? (S/N) n
Fim da Execução!

In [ ]:
#Solução simples usando o range aí
extensos = ('zero', 'um', 'dois', 'três','quatro', 'cinco',
            'seis', 'sete', 'oito','nove','dez', 'onze',
            'doze', 'treze', 'quatorze','quinze', 'dezesseis',
            'dezessete', 'dezoito', 'dezenove', 'vinte')
numero = int(input('Digite um numero de 0 a 20: '))
while numero not in range(0,21):
	numero = int(input('Tente novamente.Digite um numero de 0 a 20: '))
print(f'Você digitou o numero {extensos[numero]}!')

Digite um numero de 0 a 20: 5
Você digitou o numero cinco!

In [ ]:
paises = ('Gâmbia Banjul', 'Gana Acra', 'Guiné Conacri', 'Guiné Equatorial',	'Malabo', 'Guiné-Bissau',
          'Bissau', 'Jibuti',	'Jibuti', 'Lesoto', 'Maseru', 'Libéria', 'Monróvia', 'Líbia',	'Trípoli',
          'Madagáscar', 'Antananarivo', 'Maláui', 'Lilôngue', 'Mali',	'Bamaco', 'Marrocos', 'Rebate',
          'Maurícia', 'Porto Luís', 'Mauritânia', 'Nuaquechote', 'Moçambique',	'Maputo', 'Namíbia')
print('-='*15)
print(f'lista de alguns paises: {paises}')
print('-='*15)
print(f'os cinco primeiros são: {paises[:5]}')
print('-='*15)
print(f'os quatro ultimos são: {paises[-4:]}')
print('-='*15)
print(f'em ordem alfabetica: {sorted(paises)}')
print('-='*15)
print(f'o Maseru está na posição {paises.index("Maseru")+1}')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
lista de alguns paises: ('Gâmbia Banjul', 'Gana Acra', 'Guiné Conacri', 'Guiné Equatorial', 'Malabo', 'Guiné-Bissau', 'Bissau', 'Jibuti', 'Jibuti', 'Lesoto', 'Maseru', 'Libéria', 'Monróvia', 'Líbia', 'Trípoli', 'Madagáscar', 'Antananarivo', 'Maláui', 'Lilôngue', 'Mali', 'Bamaco', 'Marrocos', 'Rebate', 'Maurícia', 'Porto Luís', 'Mauritânia', 'Nuaquechote', 'Moçambique', 'Maputo', 'Namíbia')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
os cinco primeiros são: ('Gâmbia Banjul', 'Gana Acra', 'Guiné Conacri', 'Guiné Equatorial', 'Malabo')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
os quatro ultimos são: ('Nuaquechote', 'Moçambique', 'Maputo', 'Namíbia')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
em ordem alfabetica: ['Antananarivo', 'Bamaco', 'Bissau', 'Gana Acra', 'Guiné Conacri', 'Guiné Equatorial', 'Guiné-Bissau', 'Gâmbia Banjul', 'Jibuti', 'Jibuti', 'Lesoto', 'Libéria', 'Lilôngue', 'Líbia', 'Madagáscar', 'Malabo', 'Mali', 'Maláui', 'Maputo', 'Marrocos', 'Maseru', 'Mauritânia', 'Maurícia', 'Monróvia', 'Moçambique', 'Namíbia', 'Nuaquechote', 'Porto Luís', 'Rebate', 'Trípoli']
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
o Maseru está na posição 11

In [ ]:
from random import randint
n = (randint(0,10), randint(0,10), randint(0,10), randint(0,10), randint(0,10))
print(f'os valores soteados foram: ', end='')
for i in n:
  print(f'{i} ', end='')
print(f'\no maior valor sorteado foi: {max(n)}')
print(f'o menor valor sorteado foi: {min(n)}')

os valores soteados foram: 3 2 2 8 7
o maior valor sorteado foi: 8
o menor valor sorteado foi: 2

In [ ]:
cont9 = tres = 0
valores = (int(input('digite o valor: ')),
           int(input('digite o valor: ')),
           int(input('digite o valor: ')),
           int(input('digite o valor: ')))
print(f'você digitou os valores {valores}')
pares = []
for j in valores:
  if j == 9:
    cont9 += 1
  if j % 2 == 0:
    pares.append(j)
for k, v in enumerate(valores):
  if v == 3:
    tres = k
print(f'o valor 3 foi encontrado nas posições {tres}')
print(f'o valor 9 foi digitado {cont9} vezes')
print(f'os valores pares digitados foram {pares}')

digite o valor: 9
digite o valor: 3
digite o valor: 2
digite o valor: 8
você digitou os valores (9, 3, 2, 8)
o valor 3 foi encontrado nas posições 1
o valor 9 foi digitado 1 vezes
os valores pares digitados foram [2, 8]

In [ ]:
#ou
valores = (int(input('digite o valor: ')),
           int(input('digite o valor: ')),
           int(input('digite o valor: ')),
           int(input('digite o valor: ')))
print(f'você digitou os valores {valores}')
print(f'o numero nove apareceu {valores.count(9)} vezes')
if 3 in valores:
  print(f'o valor 3 apareceu na {valores.index(3)+1} posição')
else:
  print('o valor 3 não está presente nessa tupla')
print('os valores pares digitados são: ', end='')
for j in valores:
  if j % 2 == 0:
    print(f'{j }', end=' ')

digite o valor: 6
digite o valor: 2
digite o valor: 3
digite o valor: 9
você digitou os valores (6, 2, 3, 9)
o numero nove apareceu 1 vezes
o valor 3 apareceu na 3 posição
os valores pares digitados são: 6, 2,

In [ ]:
listagem = ('lapis', 3.50, 'borracha', 2.54, 'caneta', 3.43,
            'caderno', 5.00, 'bolsinha', 7.80, 'mochila', 50.00,
            'marcador', 3.40, 'pincel', 3.70)
print('-'*30)
print(f'{"Listagem de Preços":^30}')
print('-'*30)
for pos in range(0, len(listagem)):
  if pos % 2 == 0:                      #faz isso para pegar o nome do produto, repare que nessa tupla ele está sempre na posição par
    print(f'{listagem[pos]:.<30}', end=" ")
  else:
    print(f'R$ {listagem[pos]:>5.2f}')

------------------------------
      Listagem de Preços
------------------------------
lapis......................... R$  3.50
borracha...................... R$  2.54
caneta........................ R$  3.43
caderno....................... R$  5.00
bolsinha...................... R$  7.80
mochila....................... R$ 50.00
marcador...................... R$  3.40
pincel........................ R$  3.70

In [ ]:
palavras = ('aprender', 'programar', 'linguagem', 'python',
            'cruso', 'grátis', 'estudar', 'pratica', 'trabalhar',
            'mercado', 'programador', 'futuro')
for p in palavras:
  print(f'\nna palavra {p.upper()} temos ', end='')
  for letra in p:
    if letra in "aeiou":
      print(letra, end='')

na palavra APRENDER temos aee
na palavra PROGRAMAR temos oaa
na palavra LINGUAGEM temos iuae
na palavra PYTHON temos o
na palavra CRUSO temos uo
na palavra GRÁTIS temos i
na palavra ESTUDAR temos eua
na palavra PRATICA temos aia
na palavra TRABALHAR temos aaa
na palavra MERCADO temos eao
na palavra PROGRAMADOR temos oaao
na palavra FUTURO temos uuo

LISTAS - parte 1

In [ ]:
#podem ser modificadas
lanche = ['hamburger', 'suco', 'pizza', 'pudim']
lanche.append('cookie')
print(lanche)
lanche.insert(0,'nugget')
print(lanche)
del lanche[3]
print(lanche)
lanche.pop(3)
print(lanche)
lanche.remove('suco')
print(lanche)
if 'pizza' in lanche:
  lanche.remove('pizza')
lanche.pop()
print(lanche)

['hamburger', 'suco', 'pizza', 'pudim', 'cookie']
['nugget', 'hamburger', 'suco', 'pizza', 'pudim', 'cookie']
['nugget', 'hamburger', 'suco', 'pudim', 'cookie']
['nugget', 'hamburger', 'suco', 'cookie']
['nugget', 'hamburger', 'cookie']
['nugget', 'hamburger']

In [ ]:
valores = list(range(4,11))    #criou uma lista
print(valores)

[4, 5, 6, 7, 8, 9, 10]

In [ ]:
valores = [1,5,6,7,8,43,3,6,456,6]
valores.sort()    #colocar em ordem
print(valores)
valores.sort(reverse = True)
print(valores)

[1, 3, 5, 6, 6, 6, 7, 8, 43, 456]
[456, 43, 8, 7, 6, 6, 6, 5, 3, 1]

In [ ]:
L = [1,3,5,88,5,6,4,6,7,43,5,7,6,6,43,6,7]
if 6 in L:
  while 6 in L:
    L.remove(6)
    print(L)
else:
  print('6 não está presente na lista')

[1, 3, 5, 88, 5, 4, 6, 7, 43, 5, 7, 6, 6, 43, 6, 7]
[1, 3, 5, 88, 5, 4, 7, 43, 5, 7, 6, 6, 43, 6, 7]
[1, 3, 5, 88, 5, 4, 7, 43, 5, 7, 6, 43, 6, 7]
[1, 3, 5, 88, 5, 4, 7, 43, 5, 7, 43, 6, 7]
[1, 3, 5, 88, 5, 4, 7, 43, 5, 7, 43, 7]

In [ ]:
valores = []
print('Vamos adicionar valores na nossa lista!')
quant = int(input('quantos valores quer adicionar? '))
for i in range(1, quant+1):
  n = int(input('digite o numero a ser adicionado: '))
  valores.append(n)
print(valores)
valores.sort()
print(f'A lista ordenada: {valores}')

Vamos adicionar valores na nossa lista!
quantos valores quer adicionar? 5
digite o numero a ser adicionado: 6
digite o numero a ser adicionado: 9
digite o numero a ser adicionado: 2
digite o numero a ser adicionado: 4
digite o numero a ser adicionado: 2
[6, 9, 2, 4, 2]
A lista ordenada: [2, 2, 4, 6, 9]

In [ ]:
valores = []
valores.append(3)
valores.append(5)
valores.append(7)
for a in valores:        #esse a foi criado do nada, tirado do cu
  print(f'{a}...')

3...
5...
7...

In [ ]:
valores = []
valores.append(3)
valores.append(5)
valores.append(7)
for c, v in enumerate(valores):     #tirou do cu esse enumerate também
  print(f'Na posição {c} encontrei o valor {v}...')

Na posição 0 encontrei o valor 3...
Na posição 1 encontrei o valor 5...
Na posição 2 encontrei o valor 7...

In [ ]:
valores = []
for cont in range(0,5):
  valores.append(int(input('digite o valor a ser adicionado: ')))
print(valores)

digite o valor a ser adicionado: 2
digite o valor a ser adicionado: 5
digite o valor a ser adicionado: 4
digite o valor a ser adicionado: 99
digite o valor a ser adicionado: 6
[2, 5, 4, 99, 6]

In [ ]:
a = [2, 3, 5, 9]
print(a)
print('apos alteração')
b = a
b[2] = 8
print(f'a lista a: {a}')
print(f'a lista b: {b}')
#no python, quando igualamos uma lista a outra, quando alterarmos
#uma, a outra também sofrerá a alteração

[2, 3, 5, 9]
apos alteração
a lista a: [2, 3, 8, 9]
a lista b: [2, 3, 8, 9]

In [ ]:
a = [2, 3, 5, 9]
b = a[:]   #dessa forma, a lista b recebe uma cópia da lista a, e não ocorrerá uma associação entre as duas, como ocorrido acima
b[2] = 8
print(f'a lista a: {a}')
print(f'a lista b: {b}')
#note que a mudança executada afetou apenas a lista b

a lista a: [2, 3, 5, 9]
a lista b: [2, 3, 8, 9]

Exercicios de lista - parte 1

In [ ]:
L = []
maior = 0
menor = 0
for i in range(0,5):
  L.append(int(input(f'digite o valor para a posicão {i}: ')))
  if i == 0:
    maior = menor = L[i]
  else:
    if L[i] < menor:
      menor = L[i]
    elif L[i] > maior:
      maior = L[i]
print('='*30)
print(f'você digitou os valores {L}')
print(f'o maior valor digitado foi o {maior} na posição ', end='')
for i, v  in enumerate(L):
  if v == maior:
    print(f'{i}...', end='')
print()
print(f'o menor valor digitado foi o {menor} na posição ', end='')
for i, v in enumerate(L):
  if v == menor:
    print(f'{i}...', end='')
print()

digite o valor para a posicão 0: 4
digite o valor para a posicão 1: 7
digite o valor para a posicão 2: 6
digite o valor para a posicão 3: 6
digite o valor para a posicão 4: 7
==============================
você digitou os valores [4, 7, 6, 6, 7]
o maior valor digitado foi o 7 na posição 1...4...
o menor valor digitado foi o 4 na posição 0...

In [ ]:
#ou assim
lista = []
posicao_maior = []
posicao_menor = []
for p in range(0, 5):
    val = int(input(f'Digite um valor na posição {p}: '))
    lista.append(val)
for posicao, valores in enumerate(lista):
    if valores == max(lista):
        posicao_maior.append(posicao)
    if valores == min(lista):
        posicao_menor.append(posicao)
print(f'Você digitou os valores {lista}')
print(f'O maior valor da lista é {max(lista)}, nas posições {posicao_maior}')
print(f'O menor valor da lista é {min(lista)}, nas posições {posicao_menor}')

Digite um valor na posição 0: 6
Digite um valor na posição 1: 4
Digite um valor na posição 2: 7
Digite um valor na posição 3: 4
Digite um valor na posição 4: 7
Você digitou os valores [6, 4, 7, 4, 7]
O maior valor da lista é 7, nas posições [2, 4]
O menor valor da lista é 4, nas posições [1, 3]

In [ ]:
lista=[]
resposta=""
while resposta in "S":
    num=int(input("Digite um valor: "))
    if num not in lista:
        lista.append(num)
    else:
        print("Esse numero ja existe")
    resposta=str(input("Deseja continuar? [S/N]")).upper()
    if resposta == "N":
        break
print(sorted(lista))

Digite um valor: 8
Deseja continuar? [S/N]s
Digite um valor: 3
Deseja continuar? [S/N]s
Digite um valor: 6
Deseja continuar? [S/N]n
[3, 6, 8]

In [ ]:
# ou
lista = []
while True:
    num = int(input('Digite um número inteiro: '))
    a = lista.count(num)
    if a == 0:
        lista.append(num)
        print('Número adicionado com sucesso!')
    else:
        print('Você já adicionou esse número...')
    resp = str(input('Quer continuar?[S/N] '))
    while resp not in 'SsNn':
        resp = str(input('Quer continuar?[S/N] '))
    if resp in 'Nn':
        break
novalista = sorted(lista)
print(f'Os números que você digitou foram:{novalista}')

Digite um número inteiro: 4
Número adicionado com sucesso!
Quer continuar?[S/N] s
Digite um número inteiro: 3
Número adicionado com sucesso!
Quer continuar?[S/N] n
Os números que você digitou foram:[3, 4]

In [ ]:
lista = []
for c in range(0,5):
  n = int(input('digite um valor: '))
  if c == 0 or n > lista[-1]: #se for o primeiro valor a ser adicionado ou for maior que o ultimo elemento da lista
    lista.append(n)
    print('adicionado ao final da lista')
  else:
    posicao = 0
    while posicao < len(lista):   #verifica em cada posicao da lista
      if n <= lista[posicao]:     #se o n digitado é menor ou igual ao valor que esta la
        lista.insert(posicao,n)  #insere na posicao 'posicao' o valor 'n'
        print(f'adicionado na posicao {posicao}')
        break
      posicao += 1
print('='*30)
print(f'os valores digitados em ordem foram {lista}')

digite um valor: 0
adicionado ao final da lista
digite um valor: 5
adicionado ao final da lista
digite um valor: 4
adicionado na posicao 1
digite um valor: 6
adicionado ao final da lista
digite um valor: 3
adicionado na posicao 1
==============================
os valores digitados em ordem foram [0, 3, 4, 5, 6]

In [ ]:
# ou
lista = []
for c in range(5):
    n = int(input("Digite o numero: "))
    if c == 0 or n > lista[-1]:
        lista.append(n)
    else:
        for pos, x in enumerate(lista):
            if n <= x:
                lista.insert(pos, n)
                break
print(lista)

Digite o numero: 5
Digite o numero: 6
Digite o numero: 7
Digite o numero: 4
Digite o numero: 3
[3, 4, 5, 6, 7]

In [ ]:
lista=[]
while True:
    valor= int(input("Digite um valor: "))
    lista.append(valor)

    r=str(input("Quer continuar? [S/N] "))
    if r in "sS":
      continue
    else:
        break

lista.sort(reverse=True)

print(f'Números digitados em ordem decrescente: {lista}.')
print(f' Quantidade de números digitados: {len(lista)}')

posicao = []
if 5 in lista:
    for pos, valor in enumerate(lista):
        if valor==5:
             posicao.append(pos)
    print(f'O valor 5 faz parte da lista, nas posições {posicao}')
else:
    print("O valor 5 não faz parte da lista")

Digite um valor: 4
Quer continuar? [S/N] s
Digite um valor: 3
Quer continuar? [S/N] s
Digite um valor: 6
Quer continuar? [S/N] s
Digite um valor: 5
Quer continuar? [S/N] s
Digite um valor: 5
Quer continuar? [S/N] s
Digite um valor: 5
Quer continuar? [S/N] n
Números digitados em ordem decrescente: [6, 5, 5, 5, 4, 3].
 Quantidade de números digitados: 6
O valor 5 faz parte da lista, nas posições [1, 2, 3]

In [ ]:
L1 = []
L2 = []
L3 = []
r = 's'
while r == 's':
  x = int(input('Digite um número: '))
  if x % 2 == 0 and x != 0:
    L2.append(x)
  elif x % 2 == 1 and x != 0:
    L3.append(x)
  L1.append(x)
  r = str(input('Quer continuar? [S/N] ')).strip()
  while r not in 'sSnN':
    r = str(input('Digite S ou N: '))
    if r in "sS":
      continue
    elif r in "nN":
      break
print(f'A lista com todos os valores é {L1}')
print(f'A lista com os valores pares é {L2}')
print(f'A lista com os valores impares é {L3}')

Digite um número: 5
Quer continuar? [S/N] f
Digite S ou N: s
Digite um número: 4
Quer continuar? [S/N] n
A lista com todos os valores é [5, 4]
A lista com os valores pares é [4]
A lista com os valores impares é [5]

In [ ]:
exp = str(input('digite a expressão para verificação: '))
pilha = []
for simb in exp:
  if simb == "(":
    pilha.append(simb)
  elif simb == ")":
    if len(pilha) > 0:
      pilha.pop()
    else:
      pilha.append(")")
      break
if len(pilha) == 0:
  print('sua expressão está valida!')
else:
  print('sua expressão não é valida!')

digite a expressão para verificação: (((()))
sua expressão não é valida!

In [ ]:
LISTAS - parte 2

In [ ]:
pessoas = [['pedro', 19],['maria', 25],['joana', 45]]  #lista dentro de lista
print(pessoas)
print(pessoas[0][0]) #dentro da lista pessoas mostra o 'item' 0 dentro da 'lista' 0
print(pessoas[1][1])
print(pessoas[1])
for p in pessoas:
  print({p[0]}, end='')

[['pedro', 19], ['maria', 25], ['joana', 45]]
pedro
25
['maria', 25]
{'pedro'}{'maria'}{'joana'}

In [ ]:
teste = []
teste.append('gustavo')
teste.append(25)
galera = []
galera.append(teste[:])
teste[0] = 'jose'
teste[1] = 34
galera.append(teste[:])
print(galera)

[['gustavo', 25], ['jose', 34]]

In [ ]:
galera = []
dado = []
for i in range(0,3):
  dado.append(str(input('nome: ')))
  dado.append(int(input('idade: ')))
  galera.append(dado[:])
  dado.clear()
print(galera)

nome: maria
idade: 4
nome: jose
idade: 2
nome: afonsi
idade: 5
[['maria', 4], ['jose', 2], ['afonsi', 5]]

In [ ]:
pessoas = [['pedro', 19],['maria', 25],['joana', 45]]  #lista dentro de lista
for p in pessoas:
  print(p[0])
for p in pessoas:
  if p[1] > 21:
    print(p[1])

pedro
maria
joana
25
45

In [ ]:
LISTAS - parte 2 - exercicios

In [ ]:
temp = []
princ = []
mai = menor = 0

while True:
  temp.append(str(input('nome: ')))
  temp.append(float(input('peso: ')))

  if len(princ) == 0:
    mai = menor = temp[1]
  elif len(princ) > 1:
    if temp[1] > mai:
      mai = temp[1]
    elif temp[1] < menor:
      menor = temp[1]
  princ.append(temp[:])
  temp.clear()

  resp = str(input('quer continuar? (S/N) ')).upper()
  if resp == "N":
    break
  elif resp == "S":
    continue
print()
print(f'foram cadastradas {len(princ)} pessoas')
print(princ)
print()
print(f'o maior peso foi de {mai} de ', end='')
for p in princ:
  if p[1] == mai:
    print(f'{p[0]}', end=' ')
print(f'\no menor peso foi de {menor} de ', end='')
for p in princ:
  if p[1] == menor:
    print(f'{p[0]}', end=' ')

nome: mariabe
peso: 78
quer continuar? (S/N) s
nome: 34
peso: 56
quer continuar? (S/N) s
nome: jucilete
peso: 34
quer continuar? (S/N) s
nome: cleudimar
peso: 34
quer continuar? (S/N) s
nome: ygone
peso: 98
quer continuar? (S/N) n

foram cadastradas 5 pessoas
[['mariabe', 78.0], ['34', 56.0], ['jucilete', 34.0], ['cleudimar', 34.0], ['ygone', 98.0]]

o maior peso foi de 98.0 de ygone
o menor peso foi de 34.0 de juciletecleudimar

In [ ]:
# outro modo, pego dos comentarios
todos = list()
leve = list()
pesado = list()
pesos = list()

while True:
    nome = str(input('Nome: '))
    peso = float(input('Peso: '))
    todos.append([nome, peso])
    pesos.append(peso)
    continuar = str(input('Quer continuar? [S/N] ')).upper()
    if continuar == 'N':
        break

maior = max(pesos)
menor = min(pesos)

#isso que eu tava procurando quando tentei fazer, é bem inteligente
for a in range(len(todos)):
    if todos[a][1] == maior:
        pesado.append(todos[a][0])
    if todos[a][1] == menor:
        leve.append(todos[a][0])

print('='*30)
print(todos)
print(f'Foram cadastradas {len(todos)} pessoas, \n'
      f'O maior peso foi {maior}kg. Peso de {pesado} \n'
      f'O menor peso foi {menor}kg. Peso de {leve}')

Nome: marcos
Peso: 89.9
Quer continuar? [S/N] s
Nome: maria
Peso: 56
Quer continuar? [S/N] s
Nome: clara
Peso: 56
Quer continuar? [S/N] n
==============================
[['marcos', 89.9], ['maria', 56.0], ['clara', 56.0]]
Foram cadastradas 3 pessoas,
O maior peso foi 89.9kg. Peso de ['marcos']
O menor peso foi 56.0kg. Peso de ['maria', 'clara']

In [ ]:
todos = []
pares = []
impares = []

for i in range(1, 8):
  n = int(input(f'digite o {i}º valor: '))
  if n % 2 == 0:
    pares.append(n)
  elif n % 2 == 1:
    impares.append(n)

todos.append([sorted(pares), sorted(impares)])
print(f'os numeros pares digitados foram: {pares}')
print(f'os numeros impares digitados foram: {impares}')
print(f'todos os numeros digitados: {(todos)}')

digite o 1º valor: 5
digite o 2º valor: 3
digite o 3º valor: 8
digite o 4º valor: 2
digite o 5º valor: 9
digite o 6º valor: 166
digite o 7º valor: 16
os numeros pares digitados foram: [8, 2, 166, 16]
os numeros impares digitados foram: [5, 3, 9]
todos os numeros digitados: [[[2, 8, 16, 166], [3, 5, 9]]]

In [ ]:
# ou
num = [[], []]

for i in range(1, 8):
  n = int(input(f'digite o {i}º valor: '))
  if n % 2 == 0:
    num[0].append(n)
  elif n % 2 == 1:
    num[1].append(n)

num[0].sort()
num[1].sort()
print(f'os numeros digitados foram: {num}')
print(f'os numeros pares digitados foram: {num[1]}')
print(f'os numeros impares digitados: {num[0]}')

digite o 1º valor: 9
digite o 2º valor: 3
digite o 3º valor: 2
digite o 4º valor: 16
digite o 5º valor: 8
digite o 6º valor: 3
digite o 7º valor: 4
os numeros digitados foram: [[2, 4, 8, 16], [3, 3, 9]]
os numeros pares digitados foram: [3, 3, 9]
os numeros impares digitados: [2, 4, 8, 16]

In [ ]:
#matrizes
matriz = [[],[],[]]
for l in range(0,3):
  for c in range(0,3):
    matriz[l].append(int(input(f"Digite um valor para [{l},{c}]: ")))
print('-='*30)
for l in range(0,3):
  for c in range(0,3):
    print(f'[{matriz[l][c]:^5}]', end=' ')
  print( )

Digite um valor para [0,0]: 4
Digite um valor para [0,1]: 2
Digite um valor para [0,2]: 3
Digite um valor para [1,0]: 2
Digite um valor para [1,1]: 6
Digite um valor para [1,2]: 7
Digite um valor para [2,0]: 8
Digite um valor para [2,1]: 5
Digite um valor para [2,2]: 9
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  4  ] [  2  ] [  3  ]
[  2  ] [  6  ] [  7  ]
[  8  ] [  5  ] [  9  ]

In [ ]:
matriz = [[], [], []]
somaPares = maiorSegunda = somaTerceira = 0

for l in range(0,3):
  for c in range(0,3):
    matriz[l].append(int(input(f'digite um valor para {[l, c]}: ')))

print()

for l in range(0,3):
  for c in range(0,3):
    print(f'[{matriz[l][c]:^3}]', end="")
  print()

for l in range(0,3):
  for c in range(0,3):
    if (matriz[l][c]) % 2 == 0:
      somaPares += (matriz[l][c])

for l in range(0,3):
  if c == 2:
    somaTerceira += (matriz[l][c])

#o maior da segunda coluna não funcionou desse modo, averiguar depois o erro
for c in range(0,3):
  if matriz[1][c] > maiorSegunda:
     maiorSegunda = matriz[1][c]

print()

print(f'a soma dos valores pares é {somaPares}')
print(f'a soma dos valores da terceira coluna é {somaTerceira}')
#print(f'o maior valor da segunda coluna é {max(matriz[1])}')
print(f'o maior valor da segunda coluna é {maiorSegunda}')

digite um valor para [0, 0]: 4
digite um valor para [0, 1]: 5
digite um valor para [0, 2]: 6
digite um valor para [1, 0]: 3
digite um valor para [1, 1]: 2
digite um valor para [1, 2]: 7
digite um valor para [2, 0]: 8
digite um valor para [2, 1]: 9
digite um valor para [2, 2]: 1

[ 4 ][ 5 ][ 6 ]
[ 3 ][ 2 ][ 7 ]
[ 8 ][ 9 ][ 1 ]

a soma dos valores pares é 20
a soma dos valores da terceira coluna é 14
o maior valor da segunda coluna é 7

In [ ]:
from random import randint
from time import sleep
jogos = []
lista = []
tot = 1

print('$' * 50)
print(f'{("   MEGA SENA   "):$^50}')
print('$' * 50)
quant = int(input('quantos jogos quer sortear? '))

while tot <= quant:
  cont = 0
  while True:
    num = randint(1, 60)
    if num not in lista:
      lista.append(num)
      cont += 1
    if cont >= 6:
      break
    #print(f'os numeros sorteados foram {lista}')
  jogos.append(lista[:])
  lista.clear()
  tot += 1
for a, b in enumerate(jogos):
  print(f'jogo {a+1} : {b}')
  sleep(1)
print(f"{('  Boa sorte!  '):$^50}")

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$   MEGA SENA   $$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
quantos jogos quer sortear? 3
jogo 1 : [60, 41, 53, 23, 47, 2]
jogo 2 : [22, 53, 29, 57, 46, 20]
jogo 3 : [19, 7, 16, 47, 58, 27]
$$$$$$$$$$$$$$$$$$  Boa sorte!  $$$$$$$$$$$$$$$$$$

In [ ]:
ficha = []
while True:
  nome = str(input('nome: '))
  nota1 = float(input('primeira nota: '))
  nota2 = float(input('segunda nota: '))
  media = (nota1 + nota2)/2
  ficha.append([nome, [nota1, nota2], media])
  resp = str(input('quer continuar? (S/N) '))
  if resp in "Nn":
    break
print('~'*25)
print(f"{'Nº':<4}{'Nome':<10}{'media':>8}")
print('~'*25)
for a, b in enumerate(ficha):
  print(f'{a+1:<4}{b[0]:<10}{b[2]:>8.1f}')

nome: maria
primeira nota: 7.8
segunda nota: 8.7
quer continuar? (S/N) s
nome: ygona
primeira nota: 3.4
segunda nota: 5.6
quer continuar? (S/N) n
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Nº  Nome         media
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1   maria          8.2
2   ygona          4.5

In [ ]:
Dicionarios

In [ ]:
dados = {'nome': 'Maria', 'idade': 23}
print(dados)
print(dados['nome'])
dados['sexo'] = 'M'
print(dados)
del dados['idade']
print(dados)
print(dados.values())
print(dados.keys())
print(dados.items())

{'nome': 'Maria', 'idade': 23}
Maria
{'nome': 'Maria', 'idade': 23, 'sexo': 'M'}
{'nome': 'Maria', 'sexo': 'M'}
dict_values(['Maria', 'M'])
dict_keys(['nome', 'sexo'])
dict_items([('nome', 'Maria'), ('sexo', 'M')])

In [ ]:
pessoas = {'nome': 'Marcos', 'idade': 22, 'sexo': 'M'}
print(f'o {pessoas["nome"]} tem {pessoas["idade"]} anos')  #repare que tem que ser usado aspas duplas
pessoas['nome'] = 'Leando' #trocar ou adicionar algum valor ou key, não precisa de append
print(pessoas.values())
print(pessoas.keys())
print(pessoas.items())
for k in pessoas.values():
  print(k)
for k, v in pessoas.items():
  print(f'{k} = {v}')

o Marcos tem 22 anos
dict_values(['Leando', 22, 'M'])
dict_keys(['nome', 'idade', 'sexo'])
dict_items([('nome', 'Leando'), ('idade', 22), ('sexo', 'M')])
Leando
22
M
nome = Leando
idade = 22
sexo = M

In [ ]:
filme = {'titulo': 'Star Wars', 'ano': 1977, 'diretor': 'george lucas'}
for k, v in filme.items():
  print(f'o {k} é {v}')

o titulo é Star Wars
o ano é 1977
o diretor é george lucas

In [ ]:
#colocar um dicionario dentro de uma lista
brasil = []
estado1 = {'estado': 'Rio de janeiro', 'sigla': 'RJ'}
estado2 = {'estado': 'são paulo', 'sigla':'SP'}
brasil.append(estado1)
brasil.append(estado2)
print(brasil)
print(brasil[0])
print(brasil[0]['sigla'])

[{'estado': 'Rio de janeiro', 'sigla': 'RJ'}, {'estado': 'são paulo', 'sigla': 'SP'}]
{'estado': 'Rio de janeiro', 'sigla': 'RJ'}
RJ

In [ ]:
estado = {}
brasil = []
for i in range(0,3):
  estado['uf'] = str(input('unidade federativa: '))
  estado['sigla'] = str(input('sigla: '))
  brasil.append(estado.copy())
for e in brasil:
  for k, v in e.items():
    print(f'o campo {k} tem valor {v}')

for e in brasil:
  for v in e.values():
    print(f'{v} - ', end='')
  print()

unidade federativa: minas
sigla: mg
unidade federativa: rio
sigla: rj
unidade federativa: sampa
sigla: sp
o campo uf tem valor minas
o campo sigla tem valor mg
o campo uf tem valor rio
o campo sigla tem valor rj
o campo uf tem valor sampa
o campo sigla tem valor sp
minas mg
rio rj
sampa sp

In [ ]:
DICIONARIOS - EXERCICIOS

In [ ]:
aluno = {}
aluno['nome'] = str(input('nome: '))
aluno['media'] = float(input(f'nota de {aluno["nome"]}: '))
if aluno['media'] >= 7:
  aluno['situacao'] = 'Aprovado'
elif 5 <= aluno['media'] < 7:
  aluno['situacao'] = 'Recuperação'
elif aluno['media'] < 5:
  aluno['situacao'] ='Reprovado'

print(aluno)
for index, value in aluno.items():
  print(f'{index} é igual a {value}')

nome: maria
nota de maria: 8
{'nome': 'maria', 'media': 8.0, 'situacao': 'Aprovado'}
nome é igual maria
media é igual 8.0
situacao é igual Aprovado

In [ ]:
from random import randint
from time import sleep
from operator import itemgetter
jogo = {'jogador A': randint(1,6),
        'jogador B': randint(1,6),
        'jogador C': randint(1,6),
        'jogador D': randint(1,6)}
ranking = dict()
print("valores sorteados:")
for k, v in jogo.items():
  print(f'{k} tirou {v} no dado.')
  sleep(1)
ranking = sorted(jogo.items(), key=itemgetter(1), reverse=True)
print(ranking)
for i, v in enumerate(ranking):
  print(f'{i+1}º lugar: {v[0]} com {v[1]}')
  sleep(1)

valores sorteados:
jogador A tirou 2 no dado.
jogador B tirou 3 no dado.
jogador C tirou 2 no dado.
jogador D tirou 5 no dado.
[('jogador D', 5), ('jogador B', 3), ('jogador A', 2), ('jogador C', 2)]
1º lugar: jogador D com 5
2º lugar: jogador B com 3
3º lugar: jogador A com 2
4º lugar: jogador C com 2

In [ ]:
from datetime import datetime
pessoa = {}
pessoa['nome'] = str(input('nome: '))
nasc = int(input('ano de nascimento: '))
pessoa['idade'] = datetime.now().year - nasc
pessoa['ctps'] = int(input('carteira de trabalho (0 - não tem): '))
if pessoa['ctps'] != 0:
  pessoa['contratação'] = int(input('ano de contratação: '))
  pessoa['salario'] = float(input('salário: '))
  pessoa['aposentadoria'] = pessoa['idade'] + ((pessoa['contratação'] + 35) - datetime.now().year)
print()
print('~'*50)
print()
for k, v in pessoa.items():
  print(f'{k} é {v}')

nome: bucetuda
ano de nascimento: 2000
carteira de trabalho (0 - não tem): 2345
ano de contratação: 2017
salário: 1799

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

nome é bucetuda
idade é 22
ctps é 2345
contratação é 2017
salario é 1799.0
aposentadoria é 52

In [ ]:
jogador = {}
partidas = []
jogador['nome'] = str(input('nome: '))
tot = int(input(f'quantas partidas o {jogador["nome"]} jogou? '))
for i in range(0, tot):
  partidas.append(int(input(f'quantos gols na partida {i+1}? ')))
jogador['gols'] = partidas[:]
jogador['total'] = sum(partidas)
print()
print(jogador)
print()
for k, v in jogador.items():
  print(f'{k} :: {v}')
print()
print(f'o jogador {jogador["nome"]} jogou {len(jogador["gols"])} partidas')
for i, v in enumerate(jogador['gols']):
  print(f' - na partida {i+1}, fez {v} gols')
print(f'foi um total de {jogador["total"]} gols')

nome: cleurimar
quantas partidas o cleurimar jogou? 4
quantos gols na partida 1? 2
quantos gols na partida 2? 7
quantos gols na partida 3? 4
quantos gols na partida 4? 0

{'nome': 'cleurimar', 'gols': [2, 7, 4, 0], 'total': 13}

nome :: cleurimar
gols :: [2, 7, 4, 0]
total :: 13

o jogador cleurimar jogou 4 partidas
 - na partida 1, fez 2 gols
 - na partida 2, fez 7 gols
 - na partida 3, fez 4 gols
 - na partida 4, fez 0 gols
foi um total de 13 gols

In [ ]:
galera = list ()
pessoa = dict ()
soma = media = 0
while True:
  pessoa.clear()
  pessoa['nome'] = str(input('Nome: '))
  while True:
    pessoa['sexo'] = str(input('Sexo: [M/F]: ')).upper()[0]      #esse [0] serve para pegar apenas a primeira letra digitada
    if pessoa['sexo'] in 'MF':
      break
    print('Entrada inválida, digite o sexo da pessoa [M/F].')
  pessoa['idade'] = int(input('Idade: '))
  soma += pessoa['idade']
  galera.append(pessoa.copy())          #também da pra usar pessoa.coppy()
  while True:
    resp = str(input('Quer continuar? [S/N] ')).upper()[0]
    if resp in 'SN':
      break
    print('Entrada inválida, digite a entrada correta [S/N]')
  if resp == 'N':
    break
print("~~"*15)
print(f'Ao todo temos {len(galera)} pessoas cadastradas')
media = soma / len(galera)
print(f'A média de idade é de {media:5.2f} anos')

Nome: mariane
Sexo: [M/F]: m
Idade: 12
Quer continuar? [S/N] s
Nome: claudio
Sexo: [M/F]: m
Idade: 34
Quer continuar? [S/N] s
Nome: marlune
Sexo: [M/F]: f
Idade: 23
Quer continuar? [S/N] n
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ao todo temos 3 pessoas cadastradas

In [ ]:
FUNÇÕES - PARTE 1

In [ ]:
def lin():
  print('~-'*30)

lin()
print('curso em video')
lin()
print('estou ferrada')
lin()
print('vou me suicidar')
lin()
print('odeio meu trabalho')
lin()

~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
curso em video
~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
estou ferrada
~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
vou me suicidar
~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
odeio meu trabalho
~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-

In [ ]:
def mensagem(msg):
  print('='*25)
  print(msg)
  print('='*25)

mensagem('buceta desgraçada')
mensagem('eu odeio minha vida')
mensagem('capeta')

=========================
buceta desgraçada
=========================
=========================
eu odeio minha vida
=========================
=========================
capeta
=========================

In [ ]:
def soma(a, b):
  s = a + b
  print(s)


soma(1, 7)
soma(50, 87)

8
137

In [ ]:
def contador(*num):     #* é para desempacotar, não precisar inserir sempre o mesmo tanto de caracteres
  for valor in num:
    print(f'{valor} ', end="")
  print('fim!')


contador(1,4,5,4,6,3)
contador(4,5,3)
contador(6,3,5,3,2)

1 4 5 4 6 3 fim!
4 5 3 fim!
6 3 5 3 2 fim!

In [ ]:
#exemplo melhor
def soma(*valores):
  s = 0
  for n in valores:
    s += n
  print(f'somando os {valores} temos {s}')


soma(2,4,5,4)
soma(3,5,4)

somando os (2, 4, 5, 4) temos 15
somando os (3, 5, 4) temos 12

In [ ]:
def dobra(lst):
  pos = 0
  while pos < len(lst):
    lst[pos] *= 2
    pos += 1


valores = [6,4,3,2,5,6,4]
dobra(valores)
print(f'o dobro dos valores digitados {valores}')

o dobro dos valores digitados [12, 8, 6, 4, 10, 12, 8]

In [ ]:
EXERCICIOS FUNÇÕES - PARTE 1

In [ ]:
def area(larg, comp):
  a = larg * comp
  print(f'a are de um terreno de {larg} x {comp} é de {a}m²')

print('controle de terreno')
print('-' * 20)
l = float(input('digite a largura (m): '))
c = float(input('digite o comprimento (m): '))
area(l, c)

controle de terreno
--------------------
digite a largura (m): 50
digite o comprimento (m): 90
a are de um terreno de 50.0x90.0 é de 4500.0m²

In [ ]:
from time import sleep
def contador(i, f , p):
  print(f'contagem de {i} ate {f} de {p} em {p} ')

  if i < f:
    cont = i
    while cont <= f:
      print(f'{cont} ', end='', flush=True)
      sleep(0.5)
      cont += p
    print('Fim!')
  else:
    cont = i
    while cont >= f:
      print(f'{cont} ', end='', flush=True)
      sleep(0.5)
      cont -= p
    print('fim!')

C = int(input('começo da contagem: '))
D = int(input('fim da contagem: '))
P = int(input('passo: '))
contador(C, D, P)

começo da contagem: 8
fim da contagem: 2
passo: 1
contagem de 8 ate 2 de 1 em 1
8 7 6 5 4 3 2 fim!

In [ ]:
FUNÇÕES - parte 2

In [ ]:
BIBLIOTECA NUMPY

In [ ]:
import numpy as np
m1 = np.array([[19,4,5],        #função arrays
               [23,9,2],
               [1,5,12]])
print(m1)

print()
m2 = np.array([[1,2,5]])
print(m2)

print()
zeros = np.zeros((3,3))     #função zeros
print(zeros)

print()
ones = np.ones((3,3))      #função ones
print(ones)

print()
x = np.arange(1, 25, 2)
print(x)

print()
x2 = np.array([x])
print(x2)

print()
s = m1.shape        #tamanho
print(s)
s = m1.shape[1]     #n de colunas de m1
print(s)

print()
print(m1.size)      #n de elementos na matriz
print(m1.dtype)
print(m1.max())
print(m1.ndim)      #n de dimensões
print(x.ndim)      #repare a diferença
print(m1[0,1], m1[1,1])     #mostrando o valor presente em determinada posição da matriz

[[19  4  5]
 [23  9  2]
 [ 1  5 12]]

[[1 2 5]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[ 1  3  5  7  9 11 13 15 17 19 21 23]

[[ 1  3  5  7  9 11 13 15 17 19 21 23]]

(3, 3)
3

9
int64
23
2
1
4 9

In [ ]:
print()
for linha in range(3):
  print(m1[linha, 0])      #exibindo a primeira coluna

print()
for linha in range(3):
  for coluna in range(3):
    print(m1[linha, coluna])

print()
a = m1[0:2, :]
print(a)
re_m1 = m1.reshape((9,1))     #troca o formato da matrix, no caso, de 3x3 para 9x1
print(re_m1)
onedin = m1.flatten()         #faz a mesma coisa de cima, porém a de cima tem duas dimensões e essa apenas uma.

print()
escalar = 2*m1
print(escalar)

print()
elevar = m1**2
print(elevar)

print()
seno = np.sin(m1)
print(seno)

print()
mx = np.dot(m2, m1)     #multiplicar as matrizes
print(mx)

print()
transposta = m1.T     # ou np.transpose(m1)
print(transposta)

print()
inversa = np.linalg.inv(m1)
print(inversa)

19
23
1

19
4
5
23
9
2
1
5
12

[[19  4  5]
 [23  9  2]]
[[19]
 [ 4]
 [ 5]
 [23]
 [ 9]
 [ 2]
 [ 1]
 [ 5]
 [12]]

[[38  8 10]
 [46 18  4]
 [ 2 10 24]]

[[361  16  25]
 [529  81   4]
 [  1  25 144]]

[[ 0.14987721 -0.7568025  -0.95892427]
 [-0.8462204   0.41211849  0.90929743]
 [ 0.84147098 -0.95892427 -0.53657292]]

[[70 47 69]]

[[19 23  1]
 [ 4  9  5]
 [ 5  2 12]]

[[ 0.07561728 -0.01774691 -0.02854938]
 [-0.21141975  0.1720679   0.05941358]
 [ 0.08179012 -0.07021605  0.06095679]]

In [ ]:
determinante = np.linalg.det(m1)
print(determinante)

print()

1295.9999999999998

In [ ]:
BIBLIOTECA PANDAS

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/sarviovalente/dataset_spraying_data/main/spraying_data.csv')
print(df)

        cor    vazao  pressao  altura  distancia_pontas  angulo_real  \
0    Marrom  1.89250      4.0    50.0              50.0       105.46
1    Marrom  1.89250      4.0    50.0              50.0       105.37
2    Marrom  1.89250      4.0    50.0              50.0       105.71
3       NaN      NaN      NaN     NaN               NaN          NaN
4    Marrom  1.89250      3.0    50.0              50.0       100.63
..      ...      ...      ...     ...               ...          ...
534   Verde  0.56775      3.0    70.0              70.0        83.23
535     NaN      NaN      NaN     NaN               NaN          NaN
536   Verde  0.56775      2.0    70.0              70.0        75.80
537   Verde  0.56775      2.0    70.0              70.0        74.81
538   Verde  0.56775      2.0    70.0              70.0        75.92

            cv  vazao_real
0     6.714493        2.15
1     6.899324        2.15
2     6.795350        2.15
3          NaN         NaN
4     6.059702        1.92
..         ...         ...
534   4.566385        0.60
535        NaN         NaN
536  11.314033        0.49
537  12.792705        0.49
538  10.673072        0.49

[539 rows x 8 columns]

In [ ]:
url = 'https://raw.githubusercontent.com/sarviovalente/dataset_spraying_data/main/spraying_data.csv'
df = pd.read_csv(url)
print(df)

        cor    vazao  pressao  altura  distancia_pontas  angulo_real  \
0    Marrom  1.89250      4.0    50.0              50.0       105.46
1    Marrom  1.89250      4.0    50.0              50.0       105.37
2    Marrom  1.89250      4.0    50.0              50.0       105.71
3       NaN      NaN      NaN     NaN               NaN          NaN
4    Marrom  1.89250      3.0    50.0              50.0       100.63
..      ...      ...      ...     ...               ...          ...
534   Verde  0.56775      3.0    70.0              70.0        83.23
535     NaN      NaN      NaN     NaN               NaN          NaN
536   Verde  0.56775      2.0    70.0              70.0        75.80
537   Verde  0.56775      2.0    70.0              70.0        74.81
538   Verde  0.56775      2.0    70.0              70.0        75.92

            cv  vazao_real
0     6.714493        2.15
1     6.899324        2.15
2     6.795350        2.15
3          NaN         NaN
4     6.059702        1.92
..         ...         ...
534   4.566385        0.60
535        NaN         NaN
536  11.314033        0.49
537  12.792705        0.49
538  10.673072        0.49

[539 rows x 8 columns]

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving arquivo csv aula pandas.csv to arquivo csv aula pandas.csv

In [ ]:
import io

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['arquivo csv aula pandas.csv']))
print(df)

        cor    vazao  pressao  altura  distancia_pontas  angulo_real  \
0    Marrom  1.89250      4.0    50.0              50.0       105.46
1    Marrom  1.89250      4.0    50.0              50.0       105.37
2    Marrom  1.89250      4.0    50.0              50.0       105.71
3       NaN      NaN      NaN     NaN               NaN          NaN
4    Marrom  1.89250      3.0    50.0              50.0       100.63
..      ...      ...      ...     ...               ...          ...
534   Verde  0.56775      3.0    70.0              70.0        83.23
535     NaN      NaN      NaN     NaN               NaN          NaN
536   Verde  0.56775      2.0    70.0              70.0        75.80
537   Verde  0.56775      2.0    70.0              70.0        74.81
538   Verde  0.56775      2.0    70.0              70.0        75.92

            cv  vazao_real
0     6.714493        2.15
1     6.899324        2.15
2     6.795350        2.15
3          NaN         NaN
4     6.059702        1.92
..         ...         ...
534   4.566385        0.60
535        NaN         NaN
536  11.314033        0.49
537  12.792705        0.49
538  10.673072        0.49

[539 rows x 8 columns]

In [ ]:
#a mesma logica para arquivos excel

In [ ]:
df.columns.values

array(['cor', 'vazao', 'pressao', 'altura', 'distancia_pontas',
       'angulo_real', 'cv', 'vazao_real'], dtype=object)

In [ ]:
df.head()    #podemos especificar a quantidade de linhas que queremos mostrar, basta colocar o valor dentro do parenteses

,cor,vazao,pressao,altura,distancia_pontas,angulo_real,cv,vazao_real
0,Marrom,1.8925,4.0,50.0,50.0,105.46,6.714493,2.15
1,Marrom,1.8925,4.0,50.0,50.0,105.37,6.899324,2.15
2,Marrom,1.8925,4.0,50.0,50.0,105.71,6.795350,2.15
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Marrom,1.8925,3.0,50.0,50.0,100.63,6.059702,1.92

In [ ]:
df.head(10)

,cor,vazao,pressao,altura,distancia_pontas,angulo_real,cv,vazao_real
0,Marrom,1.8925,4.0,50.0,50.0,105.46,6.714493,2.15
1,Marrom,1.8925,4.0,50.0,50.0,105.37,6.899324,2.15
2,Marrom,1.8925,4.0,50.0,50.0,105.71,6.795350,2.15
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Marrom,1.8925,3.0,50.0,50.0,100.63,6.059702,1.92
5,Marrom,1.8925,3.0,50.0,50.0,100.14,6.197276,1.92
6,Marrom,1.8925,3.0,50.0,50.0,100.79,6.290507,1.92
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Marrom,1.8925,2.0,50.0,50.0,95.47,3.979539,1.57
9,Marrom,1.8925,2.0,50.0,50.0,95.50,4.293144,1.57

In [ ]:
df.tail(10)

,cor,vazao,pressao,altura,distancia_pontas,angulo_real,cv,vazao_real
529,Verde,0.56775,4.0,70.0,70.0,89.91,5.053137,0.69
530,Verde,0.56775,4.0,70.0,70.0,89.70,5.558428,0.69
531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,Verde,0.56775,3.0,70.0,70.0,83.73,3.344968,0.60
533,Verde,0.56775,3.0,70.0,70.0,83.33,3.271244,0.60
534,Verde,0.56775,3.0,70.0,70.0,83.23,4.566385,0.60
535,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536,Verde,0.56775,2.0,70.0,70.0,75.80,11.314033,0.49
537,Verde,0.56775,2.0,70.0,70.0,74.81,12.792705,0.49
538,Verde,0.56775,2.0,70.0,70.0,75.92,10.673072,0.49

In [ ]:
df = df.dropna()